trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: "1.13.3"
  workingDirectory: "terraform"
  serviceConnection: "sc-azure-terraform-devops"

stages:
  # ============================================================
  # VALIDATE
  # ============================================================
  - stage: Validate
    displayName: Terraform Validate

    jobs:
      - job: Validate
        displayName: Validate Terraform

        steps:
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: $(terraformVersion)

          - task: AzureCLI@2
            displayName: Terraform Init and Validate
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(workingDirectory)

              inlineScript: |
                set -e

                echo "Azure subscription:"
                az account show --query "{name:name, id:id}" -o table

                export ARM_SUBSCRIPTION_ID="$(az account show --query id -o tsv)"

                echo "Terraform version:"
                terraform version

                terraform init -input=false

                terraform fmt -recursive

                terraform validate

  # ============================================================
  # PLAN
  # ============================================================
  - stage: Plan
    displayName: Terraform Plan

    dependsOn: Validate

    jobs:
      - job: Plan
        displayName: Generate Terraform Plan

        steps:
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: $(terraformVersion)

          - task: AzureCLI@2
            displayName: Terraform Plan
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(workingDirectory)

              inlineScript: |
                set -e

                echo "Azure subscription:"
                az account show --query "{name:name, id:id}" -o table

                export ARM_SUBSCRIPTION_ID="$(az account show --query id -o tsv)"

                terraform init -input=false

                terraform plan \
                  -input=false \
                  -var-file="env/dev.tfvars" \
                  -out=tfplan

          - publish: $(workingDirectory)/tfplan
            artifact: terraform-plan
            displayName: Publish Terraform Plan
