trigger: none

parameters:
  - name: environment
    displayName: Environment to destroy
    type: string
    default: dev
    values:
      - dev
      - prod

variables:
  terraformVersion: "1.13.3"
  workingDirectory: "terraform"
  serviceConnection: "sc-azure-terraform-devops"

stages:
  - template: pipelines/templates/terraform-destroy.yml
    parameters:
      environment: ${{ parameters.environment }}
